#!/bin/bash

########################
# include the magic
# Check it out from here: https://github.com/paxtonhare/demo-magic
########################
# In my env, this is how it's initiated
. ~/workspaces/bash/demo-magic/demo-magic.sh

# Ready
clear

# Prerequisites
p "# What are the prerequisites? Well, just Docker, or Podman (which is Docker compatible)"
pe "docker --version"

p "# Typically, you may want to run things in a dedicated network. Let's create a network named \"my-network\""
pe "docker network create my-network"
pe "docker network ls" 

p "# That's all we need as the prerequisites"

# Get started
p "# Now, let's get started."
p "# Firstly, let's see what commands are supported"
pe "vind -h"

# CMD: config create
p "# To start, we need to prepare a config yaml file, which can be generated by command."
p "vind config create -n cluster -k cluster-key -s ubuntu --networks my-network -r 2 -i brightzheng100/vind-ubuntu:22.04 -c ubuntu-1.yaml"
p "# Let's have a look at the generated \"ubuntu-1.yaml\" file"
pe "cat ubuntu-1.yaml"

# CMD: create (single machine)
p "# Now, let's create the cluster"
pe "vind create -c ubuntu-1.yaml"

# CMD: show
p "# Great, let's see what we've created"
pe "vind show -c ubuntu-1.yaml"
p "# Well, they're actually Docker containers"
pe "docker ps"

# CMD: ssh (manually exit demo magic is needed)
p "# How does the VM experience look like?"
p "# Firstly, ssh into it"
pe "vind ssh ubuntu-node0 -c ubuntu-1.yaml"
# in the VM, do something like
# whoami
# cat /etc/os-release
# sudo apt-get update
# sudo apt-get install apache2
# sudo systemctl start apache2
# sudo systemctl status apache2
# curl -I localhost
# ps aux

# CMD: stop & start
p "# We can stop and start the specific machine(s)"
pe "vind stop ubuntu-node0 -c ubuntu-1.yaml"
pe "vind start ubuntu-node0 -c ubuntu-1.yaml"
p "# Or all machines"
pe "vind stop -c ubuntu-1.yaml"
pe "vind start -c ubuntu-1.yaml"

# CMD: delete
p "# Once the job is done, the machines can be disposed easily"
pe "vind delete -c ubuntu-1.yaml"

# CMD: create (multiple machine sets)
p "# How if I want to create different machine sets in one shot?"
pe "cat ubuntu-2.yaml"
pe "vind create -c ubuntu-2.yaml"
pe "docker ps"
pe "vind ssh normal-node0 -c ubuntu-2.yaml"
pe "# This is cool as my host directory is bind mounted into the machine too!"
